name: doctors_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  location: ^7.0.1
  firebase_storage: ^12.4.0
  intl: ^0.20.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets: 
    - lib/assets/images/