name: doctors_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  location: ^7.0.1
  firebase_storage: ^12.4.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.2
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.4.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.1
  dio: ^5.0.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.3
  file_picker: ^9.2.1
  logger: ^2.5.0
  geocoding: ^3.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"

flutter:

  uses-material-design: true

  assets: 
    - lib/assets/images/